# Generated by Django 4.2.1 on 2023-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('tweetid', models.IntegerField()),
                ('tweet', models.CharField(max_length=20000)),
                ('username', models.CharField(max_length=20000)),
            ],
        ),
    ]
